[
    {
        "employee_id":2,
        "name":"Employee 2",
        "title":"Salesman",
        "date_hired":"2\/28\/2015",
        "location":"Chicago",
        "sale_id":62,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":77094,
        "date_sold":"3\/7\/2021",
        "car_id":62,
        "date_listed":"3\/8\/2020"
    },
    {
        "employee_id":2,
        "name":"Employee 2",
        "title":"Salesman",
        "date_hired":"2\/28\/2015",
        "location":"Chicago",
        "sale_id":174,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":44098,
        "date_sold":"4\/30\/2023",
        "car_id":174,
        "date_listed":"5\/1\/2022"
    },
    {
        "employee_id":2,
        "name":"Employee 2",
        "title":"Salesman",
        "date_hired":"2\/28\/2015",
        "location":"Chicago",
        "sale_id":184,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":73620,
        "date_sold":"7\/9\/2023",
        "car_id":184,
        "date_listed":"7\/10\/2022"
    },
    {
        "employee_id":3,
        "name":"Employee 3",
        "title":"Manager",
        "date_hired":"3\/31\/2015",
        "location":"Miami",
        "sale_id":166,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":59136,
        "date_sold":"3\/5\/2023",
        "car_id":166,
        "date_listed":"3\/6\/2022"
    },
    {
        "employee_id":3,
        "name":"Employee 3",
        "title":"Manager",
        "date_hired":"3\/31\/2015",
        "location":"Miami",
        "sale_id":188,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":47812,
        "date_sold":"8\/6\/2023",
        "car_id":188,
        "date_listed":"8\/7\/2022"
    },
    {
        "employee_id":4,
        "name":"Employee 4",
        "title":"Salesman",
        "date_hired":"4\/30\/2015",
        "location":"Los Angeles",
        "sale_id":90,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":26643,
        "date_sold":"9\/19\/2021",
        "car_id":90,
        "date_listed":"9\/20\/2020"
    },
    {
        "employee_id":5,
        "name":"Employee 5",
        "title":"Salesman",
        "date_hired":"5\/31\/2015",
        "location":"Houston",
        "sale_id":7,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":49103,
        "date_sold":"2\/16\/2020",
        "car_id":7,
        "date_listed":"2\/17\/2019"
    },
    {
        "employee_id":5,
        "name":"Employee 5",
        "title":"Salesman",
        "date_hired":"5\/31\/2015",
        "location":"Houston",
        "sale_id":37,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":51468,
        "date_sold":"9\/13\/2020",
        "car_id":37,
        "date_listed":"9\/15\/2019"
    },
    {
        "employee_id":5,
        "name":"Employee 5",
        "title":"Salesman",
        "date_hired":"5\/31\/2015",
        "location":"Houston",
        "sale_id":41,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":24924,
        "date_sold":"10\/11\/2020",
        "car_id":41,
        "date_listed":"10\/13\/2019"
    },
    {
        "employee_id":5,
        "name":"Employee 5",
        "title":"Salesman",
        "date_hired":"5\/31\/2015",
        "location":"Houston",
        "sale_id":77,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":32937,
        "date_sold":"6\/20\/2021",
        "car_id":77,
        "date_listed":"6\/21\/2020"
    },
    {
        "employee_id":6,
        "name":"Employee 6",
        "title":"Salesman",
        "date_hired":"6\/30\/2015",
        "location":"Chicago",
        "sale_id":86,
        "car_make":"BMW",
        "car_model":"Model X",
        "price":61066,
        "date_sold":"8\/22\/2021",
        "car_id":86,
        "date_listed":"8\/23\/2020"
    },
    {
        "employee_id":6,
        "name":"Employee 6",
        "title":"Salesman",
        "date_hired":"6\/30\/2015",
        "location":"Chicago",
        "sale_id":115,
        "car_make":"Toyota",
        "car_model":"Civic",
        "price":78747,
        "date_sold":"3\/13\/2022",
        "car_id":115,
        "date_listed":"3\/14\/2021"
    },
    {
        "employee_id":6,
        "name":"Employee 6",
        "title":"Salesman",
        "date_hired":"6\/30\/2015",
        "location":"Chicago",
        "sale_id":126,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":50310,
        "date_sold":"5\/29\/2022",
        "car_id":126,
        "date_listed":"5\/30\/2021"
    },
    {
        "employee_id":6,
        "name":"Employee 6",
        "title":"Salesman",
        "date_hired":"6\/30\/2015",
        "location":"Chicago",
        "sale_id":132,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":42900,
        "date_sold":"7\/10\/2022",
        "car_id":132,
        "date_listed":"7\/11\/2021"
    },
    {
        "employee_id":6,
        "name":"Employee 6",
        "title":"Salesman",
        "date_hired":"6\/30\/2015",
        "location":"Chicago",
        "sale_id":185,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":79926,
        "date_sold":"7\/16\/2023",
        "car_id":185,
        "date_listed":"7\/17\/2022"
    },
    {
        "employee_id":6,
        "name":"Employee 6",
        "title":"Salesman",
        "date_hired":"6\/30\/2015",
        "location":"Chicago",
        "sale_id":186,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":41526,
        "date_sold":"7\/23\/2023",
        "car_id":186,
        "date_listed":"7\/24\/2022"
    },
    {
        "employee_id":7,
        "name":"Employee 7",
        "title":"Salesman",
        "date_hired":"7\/31\/2015",
        "location":"Miami",
        "sale_id":4,
        "car_make":"Toyota",
        "car_model":"Civic",
        "price":64016,
        "date_sold":"1\/26\/2020",
        "car_id":4,
        "date_listed":"1\/27\/2019"
    },
    {
        "employee_id":7,
        "name":"Employee 7",
        "title":"Salesman",
        "date_hired":"7\/31\/2015",
        "location":"Miami",
        "sale_id":21,
        "car_make":"BMW",
        "car_model":"Model X",
        "price":68903,
        "date_sold":"5\/24\/2020",
        "car_id":21,
        "date_listed":"5\/26\/2019"
    },
    {
        "employee_id":7,
        "name":"Employee 7",
        "title":"Salesman",
        "date_hired":"7\/31\/2015",
        "location":"Miami",
        "sale_id":54,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":77012,
        "date_sold":"1\/10\/2021",
        "car_id":54,
        "date_listed":"1\/12\/2020"
    },
    {
        "employee_id":7,
        "name":"Employee 7",
        "title":"Salesman",
        "date_hired":"7\/31\/2015",
        "location":"Miami",
        "sale_id":141,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":38619,
        "date_sold":"9\/11\/2022",
        "car_id":141,
        "date_listed":"9\/12\/2021"
    },
    {
        "employee_id":8,
        "name":"Employee 8",
        "title":"Manager",
        "date_hired":"8\/31\/2015",
        "location":"Miami",
        "sale_id":10,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":46493,
        "date_sold":"3\/8\/2020",
        "car_id":10,
        "date_listed":"3\/10\/2019"
    },
    {
        "employee_id":8,
        "name":"Employee 8",
        "title":"Manager",
        "date_hired":"8\/31\/2015",
        "location":"Miami",
        "sale_id":120,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":54826,
        "date_sold":"4\/17\/2022",
        "car_id":120,
        "date_listed":"4\/18\/2021"
    },
    {
        "employee_id":9,
        "name":"Employee 9",
        "title":"Manager",
        "date_hired":"9\/30\/2015",
        "location":"Chicago",
        "sale_id":20,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":26505,
        "date_sold":"5\/17\/2020",
        "car_id":20,
        "date_listed":"5\/19\/2019"
    },
    {
        "employee_id":9,
        "name":"Employee 9",
        "title":"Manager",
        "date_hired":"9\/30\/2015",
        "location":"Chicago",
        "sale_id":85,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":45908,
        "date_sold":"8\/15\/2021",
        "car_id":85,
        "date_listed":"8\/16\/2020"
    },
    {
        "employee_id":9,
        "name":"Employee 9",
        "title":"Manager",
        "date_hired":"9\/30\/2015",
        "location":"Chicago",
        "sale_id":87,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":35125,
        "date_sold":"8\/29\/2021",
        "car_id":87,
        "date_listed":"8\/30\/2020"
    },
    {
        "employee_id":9,
        "name":"Employee 9",
        "title":"Manager",
        "date_hired":"9\/30\/2015",
        "location":"Chicago",
        "sale_id":158,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":51582,
        "date_sold":"1\/8\/2023",
        "car_id":158,
        "date_listed":"1\/9\/2022"
    },
    {
        "employee_id":9,
        "name":"Employee 9",
        "title":"Manager",
        "date_hired":"9\/30\/2015",
        "location":"Chicago",
        "sale_id":159,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":40204,
        "date_sold":"1\/15\/2023",
        "car_id":159,
        "date_listed":"1\/16\/2022"
    },
    {
        "employee_id":9,
        "name":"Employee 9",
        "title":"Manager",
        "date_hired":"9\/30\/2015",
        "location":"Chicago",
        "sale_id":177,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":78433,
        "date_sold":"5\/21\/2023",
        "car_id":177,
        "date_listed":"5\/22\/2022"
    },
    {
        "employee_id":10,
        "name":"Employee 10",
        "title":"Manager",
        "date_hired":"10\/31\/2015",
        "location":"Houston",
        "sale_id":55,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":26839,
        "date_sold":"1\/17\/2021",
        "car_id":55,
        "date_listed":"1\/19\/2020"
    },
    {
        "employee_id":10,
        "name":"Employee 10",
        "title":"Manager",
        "date_hired":"10\/31\/2015",
        "location":"Houston",
        "sale_id":144,
        "car_make":"Honda",
        "car_model":"Civic",
        "price":34729,
        "date_sold":"10\/2\/2022",
        "car_id":144,
        "date_listed":"10\/3\/2021"
    },
    {
        "employee_id":11,
        "name":"Employee 11",
        "title":"Salesman",
        "date_hired":"11\/30\/2015",
        "location":"Houston",
        "sale_id":93,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":51475,
        "date_sold":"10\/10\/2021",
        "car_id":93,
        "date_listed":"10\/11\/2020"
    },
    {
        "employee_id":11,
        "name":"Employee 11",
        "title":"Salesman",
        "date_hired":"11\/30\/2015",
        "location":"Houston",
        "sale_id":175,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":26849,
        "date_sold":"5\/7\/2023",
        "car_id":175,
        "date_listed":"5\/8\/2022"
    },
    {
        "employee_id":12,
        "name":"Employee 12",
        "title":"Manager",
        "date_hired":"12\/31\/2015",
        "location":"Los Angeles",
        "sale_id":23,
        "car_make":"Toyota",
        "car_model":"Civic",
        "price":46072,
        "date_sold":"6\/7\/2020",
        "car_id":23,
        "date_listed":"6\/9\/2019"
    },
    {
        "employee_id":12,
        "name":"Employee 12",
        "title":"Manager",
        "date_hired":"12\/31\/2015",
        "location":"Los Angeles",
        "sale_id":51,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":61883,
        "date_sold":"12\/20\/2020",
        "car_id":51,
        "date_listed":"12\/22\/2019"
    },
    {
        "employee_id":12,
        "name":"Employee 12",
        "title":"Manager",
        "date_hired":"12\/31\/2015",
        "location":"Los Angeles",
        "sale_id":112,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":58076,
        "date_sold":"2\/20\/2022",
        "car_id":112,
        "date_listed":"2\/21\/2021"
    },
    {
        "employee_id":14,
        "name":"Employee 14",
        "title":"Manager",
        "date_hired":"2\/29\/2016",
        "location":"Los Angeles",
        "sale_id":150,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":60274,
        "date_sold":"11\/13\/2022",
        "car_id":150,
        "date_listed":"11\/14\/2021"
    },
    {
        "employee_id":15,
        "name":"Employee 15",
        "title":"Finance Officer",
        "date_hired":"3\/31\/2016",
        "location":"Miami",
        "sale_id":25,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":51231,
        "date_sold":"6\/21\/2020",
        "car_id":25,
        "date_listed":"6\/23\/2019"
    },
    {
        "employee_id":15,
        "name":"Employee 15",
        "title":"Finance Officer",
        "date_hired":"3\/31\/2016",
        "location":"Miami",
        "sale_id":89,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":30784,
        "date_sold":"9\/12\/2021",
        "car_id":89,
        "date_listed":"9\/13\/2020"
    },
    {
        "employee_id":15,
        "name":"Employee 15",
        "title":"Finance Officer",
        "date_hired":"3\/31\/2016",
        "location":"Miami",
        "sale_id":109,
        "car_make":"Honda",
        "car_model":"Civic",
        "price":75908,
        "date_sold":"1\/30\/2022",
        "car_id":109,
        "date_listed":"1\/31\/2021"
    },
    {
        "employee_id":15,
        "name":"Employee 15",
        "title":"Finance Officer",
        "date_hired":"3\/31\/2016",
        "location":"Miami",
        "sale_id":162,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":77768,
        "date_sold":"2\/5\/2023",
        "car_id":162,
        "date_listed":"2\/6\/2022"
    },
    {
        "employee_id":16,
        "name":"Employee 16",
        "title":"Salesman",
        "date_hired":"4\/30\/2016",
        "location":"Chicago",
        "sale_id":24,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":61805,
        "date_sold":"6\/14\/2020",
        "car_id":24,
        "date_listed":"6\/16\/2019"
    },
    {
        "employee_id":16,
        "name":"Employee 16",
        "title":"Salesman",
        "date_hired":"4\/30\/2016",
        "location":"Chicago",
        "sale_id":154,
        "car_make":"BMW",
        "car_model":"Model X",
        "price":52805,
        "date_sold":"12\/11\/2022",
        "car_id":154,
        "date_listed":"12\/12\/2021"
    },
    {
        "employee_id":16,
        "name":"Employee 16",
        "title":"Salesman",
        "date_hired":"4\/30\/2016",
        "location":"Chicago",
        "sale_id":192,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":20304,
        "date_sold":"9\/3\/2023",
        "car_id":192,
        "date_listed":"9\/4\/2022"
    },
    {
        "employee_id":17,
        "name":"Employee 17",
        "title":"Manager",
        "date_hired":"5\/31\/2016",
        "location":"Los Angeles",
        "sale_id":118,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":21382,
        "date_sold":"4\/3\/2022",
        "car_id":118,
        "date_listed":"4\/4\/2021"
    },
    {
        "employee_id":19,
        "name":"Employee 19",
        "title":"Salesman",
        "date_hired":"7\/31\/2016",
        "location":"Chicago",
        "sale_id":45,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":24425,
        "date_sold":"11\/8\/2020",
        "car_id":45,
        "date_listed":"11\/10\/2019"
    },
    {
        "employee_id":19,
        "name":"Employee 19",
        "title":"Salesman",
        "date_hired":"7\/31\/2016",
        "location":"Chicago",
        "sale_id":121,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":30685,
        "date_sold":"4\/24\/2022",
        "car_id":121,
        "date_listed":"4\/25\/2021"
    },
    {
        "employee_id":19,
        "name":"Employee 19",
        "title":"Salesman",
        "date_hired":"7\/31\/2016",
        "location":"Chicago",
        "sale_id":173,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":75369,
        "date_sold":"4\/23\/2023",
        "car_id":173,
        "date_listed":"4\/24\/2022"
    },
    {
        "employee_id":21,
        "name":"Employee 21",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2016",
        "location":"Chicago",
        "sale_id":19,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":78008,
        "date_sold":"5\/10\/2020",
        "car_id":19,
        "date_listed":"5\/12\/2019"
    },
    {
        "employee_id":21,
        "name":"Employee 21",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2016",
        "location":"Chicago",
        "sale_id":92,
        "car_make":"Ford",
        "car_model":"Model X",
        "price":69116,
        "date_sold":"10\/3\/2021",
        "car_id":92,
        "date_listed":"10\/4\/2020"
    },
    {
        "employee_id":21,
        "name":"Employee 21",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2016",
        "location":"Chicago",
        "sale_id":127,
        "car_make":"Honda",
        "car_model":"Civic",
        "price":74323,
        "date_sold":"6\/5\/2022",
        "car_id":127,
        "date_listed":"6\/6\/2021"
    },
    {
        "employee_id":21,
        "name":"Employee 21",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2016",
        "location":"Chicago",
        "sale_id":149,
        "car_make":"Honda",
        "car_model":"Civic",
        "price":73842,
        "date_sold":"11\/6\/2022",
        "car_id":149,
        "date_listed":"11\/7\/2021"
    },
    {
        "employee_id":21,
        "name":"Employee 21",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2016",
        "location":"Chicago",
        "sale_id":167,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":51379,
        "date_sold":"3\/12\/2023",
        "car_id":167,
        "date_listed":"3\/13\/2022"
    },
    {
        "employee_id":22,
        "name":"Employee 22",
        "title":"Finance Officer",
        "date_hired":"10\/31\/2016",
        "location":"New York",
        "sale_id":116,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":20676,
        "date_sold":"3\/20\/2022",
        "car_id":116,
        "date_listed":"3\/21\/2021"
    },
    {
        "employee_id":23,
        "name":"Employee 23",
        "title":"Manager",
        "date_hired":"11\/30\/2016",
        "location":"Chicago",
        "sale_id":26,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":29422,
        "date_sold":"6\/28\/2020",
        "car_id":26,
        "date_listed":"6\/30\/2019"
    },
    {
        "employee_id":23,
        "name":"Employee 23",
        "title":"Manager",
        "date_hired":"11\/30\/2016",
        "location":"Chicago",
        "sale_id":35,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":62935,
        "date_sold":"8\/30\/2020",
        "car_id":35,
        "date_listed":"9\/1\/2019"
    },
    {
        "employee_id":23,
        "name":"Employee 23",
        "title":"Manager",
        "date_hired":"11\/30\/2016",
        "location":"Chicago",
        "sale_id":165,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":31026,
        "date_sold":"2\/26\/2023",
        "car_id":165,
        "date_listed":"2\/27\/2022"
    },
    {
        "employee_id":24,
        "name":"Employee 24",
        "title":"Finance Officer",
        "date_hired":"12\/31\/2016",
        "location":"Chicago",
        "sale_id":27,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":46046,
        "date_sold":"7\/5\/2020",
        "car_id":27,
        "date_listed":"7\/7\/2019"
    },
    {
        "employee_id":24,
        "name":"Employee 24",
        "title":"Finance Officer",
        "date_hired":"12\/31\/2016",
        "location":"Chicago",
        "sale_id":42,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":49615,
        "date_sold":"10\/18\/2020",
        "car_id":42,
        "date_listed":"10\/20\/2019"
    },
    {
        "employee_id":24,
        "name":"Employee 24",
        "title":"Finance Officer",
        "date_hired":"12\/31\/2016",
        "location":"Chicago",
        "sale_id":80,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":40851,
        "date_sold":"7\/11\/2021",
        "car_id":80,
        "date_listed":"7\/12\/2020"
    },
    {
        "employee_id":24,
        "name":"Employee 24",
        "title":"Finance Officer",
        "date_hired":"12\/31\/2016",
        "location":"Chicago",
        "sale_id":104,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":30000,
        "date_sold":"12\/26\/2021",
        "car_id":104,
        "date_listed":"12\/27\/2020"
    },
    {
        "employee_id":26,
        "name":"Employee 26",
        "title":"Finance Officer",
        "date_hired":"2\/28\/2017",
        "location":"New York",
        "sale_id":43,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":77602,
        "date_sold":"10\/25\/2020",
        "car_id":43,
        "date_listed":"10\/27\/2019"
    },
    {
        "employee_id":26,
        "name":"Employee 26",
        "title":"Finance Officer",
        "date_hired":"2\/28\/2017",
        "location":"New York",
        "sale_id":102,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":30774,
        "date_sold":"12\/12\/2021",
        "car_id":102,
        "date_listed":"12\/13\/2020"
    },
    {
        "employee_id":26,
        "name":"Employee 26",
        "title":"Finance Officer",
        "date_hired":"2\/28\/2017",
        "location":"New York",
        "sale_id":133,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":39832,
        "date_sold":"7\/17\/2022",
        "car_id":133,
        "date_listed":"7\/18\/2021"
    },
    {
        "employee_id":28,
        "name":"Employee 28",
        "title":"Manager",
        "date_hired":"4\/30\/2017",
        "location":"Los Angeles",
        "sale_id":13,
        "car_make":"Toyota",
        "car_model":"Civic",
        "price":71748,
        "date_sold":"3\/29\/2020",
        "car_id":13,
        "date_listed":"3\/31\/2019"
    },
    {
        "employee_id":28,
        "name":"Employee 28",
        "title":"Manager",
        "date_hired":"4\/30\/2017",
        "location":"Los Angeles",
        "sale_id":135,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":28077,
        "date_sold":"7\/31\/2022",
        "car_id":135,
        "date_listed":"8\/1\/2021"
    },
    {
        "employee_id":28,
        "name":"Employee 28",
        "title":"Manager",
        "date_hired":"4\/30\/2017",
        "location":"Los Angeles",
        "sale_id":137,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":51186,
        "date_sold":"8\/14\/2022",
        "car_id":137,
        "date_listed":"8\/15\/2021"
    },
    {
        "employee_id":28,
        "name":"Employee 28",
        "title":"Manager",
        "date_hired":"4\/30\/2017",
        "location":"Los Angeles",
        "sale_id":148,
        "car_make":"BMW",
        "car_model":"Civic",
        "price":44031,
        "date_sold":"10\/30\/2022",
        "car_id":148,
        "date_listed":"10\/31\/2021"
    },
    {
        "employee_id":30,
        "name":"Employee 30",
        "title":"Salesman",
        "date_hired":"6\/30\/2017",
        "location":"Los Angeles",
        "sale_id":29,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":44805,
        "date_sold":"7\/19\/2020",
        "car_id":29,
        "date_listed":"7\/21\/2019"
    },
    {
        "employee_id":31,
        "name":"Employee 31",
        "title":"Salesman",
        "date_hired":"7\/31\/2017",
        "location":"Houston",
        "sale_id":57,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":59117,
        "date_sold":"1\/31\/2021",
        "car_id":57,
        "date_listed":"2\/2\/2020"
    },
    {
        "employee_id":31,
        "name":"Employee 31",
        "title":"Salesman",
        "date_hired":"7\/31\/2017",
        "location":"Houston",
        "sale_id":172,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":72176,
        "date_sold":"4\/16\/2023",
        "car_id":172,
        "date_listed":"4\/17\/2022"
    },
    {
        "employee_id":31,
        "name":"Employee 31",
        "title":"Salesman",
        "date_hired":"7\/31\/2017",
        "location":"Houston",
        "sale_id":189,
        "car_make":"Ford",
        "car_model":"Model X",
        "price":45829,
        "date_sold":"8\/13\/2023",
        "car_id":189,
        "date_listed":"8\/14\/2022"
    },
    {
        "employee_id":33,
        "name":"Employee 33",
        "title":"Manager",
        "date_hired":"9\/30\/2017",
        "location":"New York",
        "sale_id":101,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":25794,
        "date_sold":"12\/5\/2021",
        "car_id":101,
        "date_listed":"12\/6\/2020"
    },
    {
        "employee_id":33,
        "name":"Employee 33",
        "title":"Manager",
        "date_hired":"9\/30\/2017",
        "location":"New York",
        "sale_id":191,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":62934,
        "date_sold":"8\/27\/2023",
        "car_id":191,
        "date_listed":"8\/28\/2022"
    },
    {
        "employee_id":34,
        "name":"Employee 34",
        "title":"Manager",
        "date_hired":"10\/31\/2017",
        "location":"Miami",
        "sale_id":68,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":52561,
        "date_sold":"4\/18\/2021",
        "car_id":68,
        "date_listed":"4\/19\/2020"
    },
    {
        "employee_id":34,
        "name":"Employee 34",
        "title":"Manager",
        "date_hired":"10\/31\/2017",
        "location":"Miami",
        "sale_id":69,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":72460,
        "date_sold":"4\/25\/2021",
        "car_id":69,
        "date_listed":"4\/26\/2020"
    },
    {
        "employee_id":34,
        "name":"Employee 34",
        "title":"Manager",
        "date_hired":"10\/31\/2017",
        "location":"Miami",
        "sale_id":70,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":36709,
        "date_sold":"5\/2\/2021",
        "car_id":70,
        "date_listed":"5\/3\/2020"
    },
    {
        "employee_id":34,
        "name":"Employee 34",
        "title":"Manager",
        "date_hired":"10\/31\/2017",
        "location":"Miami",
        "sale_id":107,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":79881,
        "date_sold":"1\/16\/2022",
        "car_id":107,
        "date_listed":"1\/17\/2021"
    },
    {
        "employee_id":34,
        "name":"Employee 34",
        "title":"Manager",
        "date_hired":"10\/31\/2017",
        "location":"Miami",
        "sale_id":113,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":39952,
        "date_sold":"2\/27\/2022",
        "car_id":113,
        "date_listed":"2\/28\/2021"
    },
    {
        "employee_id":34,
        "name":"Employee 34",
        "title":"Manager",
        "date_hired":"10\/31\/2017",
        "location":"Miami",
        "sale_id":122,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":58375,
        "date_sold":"5\/1\/2022",
        "car_id":122,
        "date_listed":"5\/2\/2021"
    },
    {
        "employee_id":35,
        "name":"Employee 35",
        "title":"Finance Officer",
        "date_hired":"11\/30\/2017",
        "location":"Chicago",
        "sale_id":114,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":50943,
        "date_sold":"3\/6\/2022",
        "car_id":114,
        "date_listed":"3\/7\/2021"
    },
    {
        "employee_id":35,
        "name":"Employee 35",
        "title":"Finance Officer",
        "date_hired":"11\/30\/2017",
        "location":"Chicago",
        "sale_id":178,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":46086,
        "date_sold":"5\/28\/2023",
        "car_id":178,
        "date_listed":"5\/29\/2022"
    },
    {
        "employee_id":35,
        "name":"Employee 35",
        "title":"Finance Officer",
        "date_hired":"11\/30\/2017",
        "location":"Chicago",
        "sale_id":197,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":74449,
        "date_sold":"10\/8\/2023",
        "car_id":197,
        "date_listed":"10\/9\/2022"
    },
    {
        "employee_id":37,
        "name":"Employee 37",
        "title":"Manager",
        "date_hired":"1\/31\/2018",
        "location":"Miami",
        "sale_id":12,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":63020,
        "date_sold":"3\/22\/2020",
        "car_id":12,
        "date_listed":"3\/24\/2019"
    },
    {
        "employee_id":37,
        "name":"Employee 37",
        "title":"Manager",
        "date_hired":"1\/31\/2018",
        "location":"Miami",
        "sale_id":14,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":26411,
        "date_sold":"4\/5\/2020",
        "car_id":14,
        "date_listed":"4\/7\/2019"
    },
    {
        "employee_id":37,
        "name":"Employee 37",
        "title":"Manager",
        "date_hired":"1\/31\/2018",
        "location":"Miami",
        "sale_id":103,
        "car_make":"Honda",
        "car_model":"Civic",
        "price":33630,
        "date_sold":"12\/19\/2021",
        "car_id":103,
        "date_listed":"12\/20\/2020"
    },
    {
        "employee_id":37,
        "name":"Employee 37",
        "title":"Manager",
        "date_hired":"1\/31\/2018",
        "location":"Miami",
        "sale_id":163,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":66897,
        "date_sold":"2\/12\/2023",
        "car_id":163,
        "date_listed":"2\/13\/2022"
    },
    {
        "employee_id":38,
        "name":"Employee 38",
        "title":"Salesman",
        "date_hired":"2\/28\/2018",
        "location":"New York",
        "sale_id":58,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":33152,
        "date_sold":"2\/7\/2021",
        "car_id":58,
        "date_listed":"2\/9\/2020"
    },
    {
        "employee_id":38,
        "name":"Employee 38",
        "title":"Salesman",
        "date_hired":"2\/28\/2018",
        "location":"New York",
        "sale_id":106,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":78043,
        "date_sold":"1\/9\/2022",
        "car_id":106,
        "date_listed":"1\/10\/2021"
    },
    {
        "employee_id":38,
        "name":"Employee 38",
        "title":"Salesman",
        "date_hired":"2\/28\/2018",
        "location":"New York",
        "sale_id":151,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":63109,
        "date_sold":"11\/20\/2022",
        "car_id":151,
        "date_listed":"11\/21\/2021"
    },
    {
        "employee_id":38,
        "name":"Employee 38",
        "title":"Salesman",
        "date_hired":"2\/28\/2018",
        "location":"New York",
        "sale_id":152,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":70218,
        "date_sold":"11\/27\/2022",
        "car_id":152,
        "date_listed":"11\/28\/2021"
    },
    {
        "employee_id":39,
        "name":"Employee 39",
        "title":"Manager",
        "date_hired":"3\/31\/2018",
        "location":"New York",
        "sale_id":199,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":31302,
        "date_sold":"10\/22\/2023",
        "car_id":199,
        "date_listed":"10\/23\/2022"
    },
    {
        "employee_id":40,
        "name":"Employee 40",
        "title":"Manager",
        "date_hired":"4\/30\/2018",
        "location":"Los Angeles",
        "sale_id":147,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":43087,
        "date_sold":"10\/23\/2022",
        "car_id":147,
        "date_listed":"10\/24\/2021"
    },
    {
        "employee_id":41,
        "name":"Employee 41",
        "title":"Finance Officer",
        "date_hired":"5\/31\/2018",
        "location":"Chicago",
        "sale_id":22,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":42079,
        "date_sold":"5\/31\/2020",
        "car_id":22,
        "date_listed":"6\/2\/2019"
    },
    {
        "employee_id":41,
        "name":"Employee 41",
        "title":"Finance Officer",
        "date_hired":"5\/31\/2018",
        "location":"Chicago",
        "sale_id":100,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":43134,
        "date_sold":"11\/28\/2021",
        "car_id":100,
        "date_listed":"11\/29\/2020"
    },
    {
        "employee_id":42,
        "name":"Employee 42",
        "title":"Manager",
        "date_hired":"6\/30\/2018",
        "location":"Houston",
        "sale_id":8,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":61996,
        "date_sold":"2\/23\/2020",
        "car_id":8,
        "date_listed":"2\/24\/2019"
    },
    {
        "employee_id":42,
        "name":"Employee 42",
        "title":"Manager",
        "date_hired":"6\/30\/2018",
        "location":"Houston",
        "sale_id":196,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":54688,
        "date_sold":"10\/1\/2023",
        "car_id":196,
        "date_listed":"10\/2\/2022"
    },
    {
        "employee_id":43,
        "name":"Employee 43",
        "title":"Salesman",
        "date_hired":"7\/31\/2018",
        "location":"Chicago",
        "sale_id":88,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":75673,
        "date_sold":"9\/5\/2021",
        "car_id":88,
        "date_listed":"9\/6\/2020"
    },
    {
        "employee_id":43,
        "name":"Employee 43",
        "title":"Salesman",
        "date_hired":"7\/31\/2018",
        "location":"Chicago",
        "sale_id":99,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":40179,
        "date_sold":"11\/21\/2021",
        "car_id":99,
        "date_listed":"11\/22\/2020"
    },
    {
        "employee_id":44,
        "name":"Employee 44",
        "title":"Salesman",
        "date_hired":"8\/31\/2018",
        "location":"Los Angeles",
        "sale_id":2,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":26217,
        "date_sold":"1\/12\/2020",
        "car_id":2,
        "date_listed":"1\/13\/2019"
    },
    {
        "employee_id":44,
        "name":"Employee 44",
        "title":"Salesman",
        "date_hired":"8\/31\/2018",
        "location":"Los Angeles",
        "sale_id":66,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":32093,
        "date_sold":"4\/4\/2021",
        "car_id":66,
        "date_listed":"4\/5\/2020"
    },
    {
        "employee_id":44,
        "name":"Employee 44",
        "title":"Salesman",
        "date_hired":"8\/31\/2018",
        "location":"Los Angeles",
        "sale_id":74,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":60683,
        "date_sold":"5\/30\/2021",
        "car_id":74,
        "date_listed":"5\/31\/2020"
    },
    {
        "employee_id":44,
        "name":"Employee 44",
        "title":"Salesman",
        "date_hired":"8\/31\/2018",
        "location":"Los Angeles",
        "sale_id":79,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":27061,
        "date_sold":"7\/4\/2021",
        "car_id":79,
        "date_listed":"7\/5\/2020"
    },
    {
        "employee_id":45,
        "name":"Employee 45",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2018",
        "location":"Houston",
        "sale_id":73,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":55044,
        "date_sold":"5\/23\/2021",
        "car_id":73,
        "date_listed":"5\/24\/2020"
    },
    {
        "employee_id":45,
        "name":"Employee 45",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2018",
        "location":"Houston",
        "sale_id":128,
        "car_make":"Ford",
        "car_model":"Model X",
        "price":64214,
        "date_sold":"6\/12\/2022",
        "car_id":128,
        "date_listed":"6\/13\/2021"
    },
    {
        "employee_id":45,
        "name":"Employee 45",
        "title":"Finance Officer",
        "date_hired":"9\/30\/2018",
        "location":"Houston",
        "sale_id":171,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":56954,
        "date_sold":"4\/9\/2023",
        "car_id":171,
        "date_listed":"4\/10\/2022"
    },
    {
        "employee_id":46,
        "name":"Employee 46",
        "title":"Finance Officer",
        "date_hired":"10\/31\/2018",
        "location":"Miami",
        "sale_id":72,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":34276,
        "date_sold":"5\/16\/2021",
        "car_id":72,
        "date_listed":"5\/17\/2020"
    },
    {
        "employee_id":47,
        "name":"Employee 47",
        "title":"Manager",
        "date_hired":"11\/30\/2018",
        "location":"Chicago",
        "sale_id":142,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":30957,
        "date_sold":"9\/18\/2022",
        "car_id":142,
        "date_listed":"9\/19\/2021"
    },
    {
        "employee_id":47,
        "name":"Employee 47",
        "title":"Manager",
        "date_hired":"11\/30\/2018",
        "location":"Chicago",
        "sale_id":190,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":22623,
        "date_sold":"8\/20\/2023",
        "car_id":190,
        "date_listed":"8\/21\/2022"
    },
    {
        "employee_id":49,
        "name":"Employee 49",
        "title":"Manager",
        "date_hired":"1\/31\/2019",
        "location":"New York",
        "sale_id":28,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":67379,
        "date_sold":"7\/12\/2020",
        "car_id":28,
        "date_listed":"7\/14\/2019"
    },
    {
        "employee_id":49,
        "name":"Employee 49",
        "title":"Manager",
        "date_hired":"1\/31\/2019",
        "location":"New York",
        "sale_id":65,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":75278,
        "date_sold":"3\/28\/2021",
        "car_id":65,
        "date_listed":"3\/29\/2020"
    },
    {
        "employee_id":49,
        "name":"Employee 49",
        "title":"Manager",
        "date_hired":"1\/31\/2019",
        "location":"New York",
        "sale_id":105,
        "car_make":"Honda",
        "car_model":"Civic",
        "price":25256,
        "date_sold":"1\/2\/2022",
        "car_id":105,
        "date_listed":"1\/3\/2021"
    },
    {
        "employee_id":49,
        "name":"Employee 49",
        "title":"Manager",
        "date_hired":"1\/31\/2019",
        "location":"New York",
        "sale_id":138,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":56595,
        "date_sold":"8\/21\/2022",
        "car_id":138,
        "date_listed":"8\/22\/2021"
    },
    {
        "employee_id":49,
        "name":"Employee 49",
        "title":"Manager",
        "date_hired":"1\/31\/2019",
        "location":"New York",
        "sale_id":146,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":77720,
        "date_sold":"10\/16\/2022",
        "car_id":146,
        "date_listed":"10\/17\/2021"
    },
    {
        "employee_id":50,
        "name":"Employee 50",
        "title":"Finance Officer",
        "date_hired":"2\/28\/2019",
        "location":"Los Angeles",
        "sale_id":91,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":72798,
        "date_sold":"9\/26\/2021",
        "car_id":91,
        "date_listed":"9\/27\/2020"
    },
    {
        "employee_id":50,
        "name":"Employee 50",
        "title":"Finance Officer",
        "date_hired":"2\/28\/2019",
        "location":"Los Angeles",
        "sale_id":145,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":23719,
        "date_sold":"10\/9\/2022",
        "car_id":145,
        "date_listed":"10\/10\/2021"
    },
    {
        "employee_id":51,
        "name":"Employee 51",
        "title":"Manager",
        "date_hired":"3\/31\/2019",
        "location":"Chicago",
        "sale_id":33,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":40965,
        "date_sold":"8\/16\/2020",
        "car_id":33,
        "date_listed":"8\/18\/2019"
    },
    {
        "employee_id":51,
        "name":"Employee 51",
        "title":"Manager",
        "date_hired":"3\/31\/2019",
        "location":"Chicago",
        "sale_id":64,
        "car_make":"Ford",
        "car_model":"Model Y",
        "price":48116,
        "date_sold":"3\/21\/2021",
        "car_id":64,
        "date_listed":"3\/22\/2020"
    },
    {
        "employee_id":51,
        "name":"Employee 51",
        "title":"Manager",
        "date_hired":"3\/31\/2019",
        "location":"Chicago",
        "sale_id":111,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":29213,
        "date_sold":"2\/13\/2022",
        "car_id":111,
        "date_listed":"2\/14\/2021"
    },
    {
        "employee_id":51,
        "name":"Employee 51",
        "title":"Manager",
        "date_hired":"3\/31\/2019",
        "location":"Chicago",
        "sale_id":198,
        "car_make":"BMW",
        "car_model":"Civic",
        "price":47470,
        "date_sold":"10\/15\/2023",
        "car_id":198,
        "date_listed":"10\/16\/2022"
    },
    {
        "employee_id":54,
        "name":"Employee 54",
        "title":"Manager",
        "date_hired":"6\/30\/2019",
        "location":"Miami",
        "sale_id":9,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":26676,
        "date_sold":"3\/1\/2020",
        "car_id":9,
        "date_listed":"3\/3\/2019"
    },
    {
        "employee_id":54,
        "name":"Employee 54",
        "title":"Manager",
        "date_hired":"6\/30\/2019",
        "location":"Miami",
        "sale_id":52,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":40991,
        "date_sold":"12\/27\/2020",
        "car_id":52,
        "date_listed":"12\/29\/2019"
    },
    {
        "employee_id":54,
        "name":"Employee 54",
        "title":"Manager",
        "date_hired":"6\/30\/2019",
        "location":"Miami",
        "sale_id":129,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":44485,
        "date_sold":"6\/19\/2022",
        "car_id":129,
        "date_listed":"6\/20\/2021"
    },
    {
        "employee_id":55,
        "name":"Employee 55",
        "title":"Finance Officer",
        "date_hired":"7\/31\/2019",
        "location":"Houston",
        "sale_id":15,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":22565,
        "date_sold":"4\/12\/2020",
        "car_id":15,
        "date_listed":"4\/14\/2019"
    },
    {
        "employee_id":55,
        "name":"Employee 55",
        "title":"Finance Officer",
        "date_hired":"7\/31\/2019",
        "location":"Houston",
        "sale_id":59,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":69436,
        "date_sold":"2\/14\/2021",
        "car_id":59,
        "date_listed":"2\/16\/2020"
    },
    {
        "employee_id":55,
        "name":"Employee 55",
        "title":"Finance Officer",
        "date_hired":"7\/31\/2019",
        "location":"Houston",
        "sale_id":82,
        "car_make":"Ford",
        "car_model":"Model X",
        "price":20643,
        "date_sold":"7\/25\/2021",
        "car_id":82,
        "date_listed":"7\/26\/2020"
    },
    {
        "employee_id":55,
        "name":"Employee 55",
        "title":"Finance Officer",
        "date_hired":"7\/31\/2019",
        "location":"Houston",
        "sale_id":117,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":54918,
        "date_sold":"3\/27\/2022",
        "car_id":117,
        "date_listed":"3\/28\/2021"
    },
    {
        "employee_id":55,
        "name":"Employee 55",
        "title":"Finance Officer",
        "date_hired":"7\/31\/2019",
        "location":"Houston",
        "sale_id":123,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":21892,
        "date_sold":"5\/8\/2022",
        "car_id":123,
        "date_listed":"5\/9\/2021"
    },
    {
        "employee_id":56,
        "name":"Employee 56",
        "title":"Salesman",
        "date_hired":"8\/31\/2019",
        "location":"New York",
        "sale_id":3,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":65528,
        "date_sold":"1\/19\/2020",
        "car_id":3,
        "date_listed":"1\/20\/2019"
    },
    {
        "employee_id":56,
        "name":"Employee 56",
        "title":"Salesman",
        "date_hired":"8\/31\/2019",
        "location":"New York",
        "sale_id":5,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":68846,
        "date_sold":"2\/2\/2020",
        "car_id":5,
        "date_listed":"2\/3\/2019"
    },
    {
        "employee_id":56,
        "name":"Employee 56",
        "title":"Salesman",
        "date_hired":"8\/31\/2019",
        "location":"New York",
        "sale_id":30,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":70341,
        "date_sold":"7\/26\/2020",
        "car_id":30,
        "date_listed":"7\/28\/2019"
    },
    {
        "employee_id":58,
        "name":"Employee 58",
        "title":"Finance Officer",
        "date_hired":"10\/31\/2019",
        "location":"Los Angeles",
        "sale_id":140,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":73173,
        "date_sold":"9\/4\/2022",
        "car_id":140,
        "date_listed":"9\/5\/2021"
    },
    {
        "employee_id":59,
        "name":"Employee 59",
        "title":"Finance Officer",
        "date_hired":"11\/30\/2019",
        "location":"Chicago",
        "sale_id":31,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":47831,
        "date_sold":"8\/2\/2020",
        "car_id":31,
        "date_listed":"8\/4\/2019"
    },
    {
        "employee_id":59,
        "name":"Employee 59",
        "title":"Finance Officer",
        "date_hired":"11\/30\/2019",
        "location":"Chicago",
        "sale_id":39,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":68601,
        "date_sold":"9\/27\/2020",
        "car_id":39,
        "date_listed":"9\/29\/2019"
    },
    {
        "employee_id":59,
        "name":"Employee 59",
        "title":"Finance Officer",
        "date_hired":"11\/30\/2019",
        "location":"Chicago",
        "sale_id":94,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":48410,
        "date_sold":"10\/17\/2021",
        "car_id":94,
        "date_listed":"10\/18\/2020"
    },
    {
        "employee_id":60,
        "name":"Employee 60",
        "title":"Finance Officer",
        "date_hired":"12\/31\/2019",
        "location":"Chicago",
        "sale_id":6,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":40836,
        "date_sold":"2\/9\/2020",
        "car_id":6,
        "date_listed":"2\/10\/2019"
    },
    {
        "employee_id":61,
        "name":"Employee 61",
        "title":"Manager",
        "date_hired":"1\/31\/2020",
        "location":"Houston",
        "sale_id":17,
        "car_make":"Ford",
        "car_model":"Model X",
        "price":49762,
        "date_sold":"4\/26\/2020",
        "car_id":17,
        "date_listed":"4\/28\/2019"
    },
    {
        "employee_id":61,
        "name":"Employee 61",
        "title":"Manager",
        "date_hired":"1\/31\/2020",
        "location":"Houston",
        "sale_id":48,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":46365,
        "date_sold":"11\/29\/2020",
        "car_id":48,
        "date_listed":"12\/1\/2019"
    },
    {
        "employee_id":61,
        "name":"Employee 61",
        "title":"Manager",
        "date_hired":"1\/31\/2020",
        "location":"Houston",
        "sale_id":81,
        "car_make":"Toyota",
        "car_model":"Civic",
        "price":61395,
        "date_sold":"7\/18\/2021",
        "car_id":81,
        "date_listed":"7\/19\/2020"
    },
    {
        "employee_id":61,
        "name":"Employee 61",
        "title":"Manager",
        "date_hired":"1\/31\/2020",
        "location":"Houston",
        "sale_id":84,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":45606,
        "date_sold":"8\/8\/2021",
        "car_id":84,
        "date_listed":"8\/9\/2020"
    },
    {
        "employee_id":61,
        "name":"Employee 61",
        "title":"Manager",
        "date_hired":"1\/31\/2020",
        "location":"Houston",
        "sale_id":98,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":72431,
        "date_sold":"11\/14\/2021",
        "car_id":98,
        "date_listed":"11\/15\/2020"
    },
    {
        "employee_id":62,
        "name":"Employee 62",
        "title":"Finance Officer",
        "date_hired":"2\/29\/2020",
        "location":"Chicago",
        "sale_id":131,
        "car_make":"BMW",
        "car_model":"Civic",
        "price":49412,
        "date_sold":"7\/3\/2022",
        "car_id":131,
        "date_listed":"7\/4\/2021"
    },
    {
        "employee_id":66,
        "name":"Employee 66",
        "title":"Salesman",
        "date_hired":"6\/30\/2020",
        "location":"Houston",
        "sale_id":124,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":64924,
        "date_sold":"5\/15\/2022",
        "car_id":124,
        "date_listed":"5\/16\/2021"
    },
    {
        "employee_id":67,
        "name":"Employee 67",
        "title":"Manager",
        "date_hired":"7\/31\/2020",
        "location":"Miami",
        "sale_id":11,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":54392,
        "date_sold":"3\/15\/2020",
        "car_id":11,
        "date_listed":"3\/17\/2019"
    },
    {
        "employee_id":67,
        "name":"Employee 67",
        "title":"Manager",
        "date_hired":"7\/31\/2020",
        "location":"Miami",
        "sale_id":47,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":50531,
        "date_sold":"11\/22\/2020",
        "car_id":47,
        "date_listed":"11\/24\/2019"
    },
    {
        "employee_id":67,
        "name":"Employee 67",
        "title":"Manager",
        "date_hired":"7\/31\/2020",
        "location":"Miami",
        "sale_id":56,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":71586,
        "date_sold":"1\/24\/2021",
        "car_id":56,
        "date_listed":"1\/26\/2020"
    },
    {
        "employee_id":67,
        "name":"Employee 67",
        "title":"Manager",
        "date_hired":"7\/31\/2020",
        "location":"Miami",
        "sale_id":95,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":24499,
        "date_sold":"10\/24\/2021",
        "car_id":95,
        "date_listed":"10\/25\/2020"
    },
    {
        "employee_id":67,
        "name":"Employee 67",
        "title":"Manager",
        "date_hired":"7\/31\/2020",
        "location":"Miami",
        "sale_id":139,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":64687,
        "date_sold":"8\/28\/2022",
        "car_id":139,
        "date_listed":"8\/29\/2021"
    },
    {
        "employee_id":67,
        "name":"Employee 67",
        "title":"Manager",
        "date_hired":"7\/31\/2020",
        "location":"Miami",
        "sale_id":176,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":53964,
        "date_sold":"5\/14\/2023",
        "car_id":176,
        "date_listed":"5\/15\/2022"
    },
    {
        "employee_id":69,
        "name":"Employee 69",
        "title":"Salesman",
        "date_hired":"9\/30\/2020",
        "location":"Houston",
        "sale_id":63,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":74550,
        "date_sold":"3\/14\/2021",
        "car_id":63,
        "date_listed":"3\/15\/2020"
    },
    {
        "employee_id":69,
        "name":"Employee 69",
        "title":"Salesman",
        "date_hired":"9\/30\/2020",
        "location":"Houston",
        "sale_id":83,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":29100,
        "date_sold":"8\/1\/2021",
        "car_id":83,
        "date_listed":"8\/2\/2020"
    },
    {
        "employee_id":69,
        "name":"Employee 69",
        "title":"Salesman",
        "date_hired":"9\/30\/2020",
        "location":"Houston",
        "sale_id":157,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":66331,
        "date_sold":"1\/1\/2023",
        "car_id":157,
        "date_listed":"1\/2\/2022"
    },
    {
        "employee_id":70,
        "name":"Employee 70",
        "title":"Manager",
        "date_hired":"10\/31\/2020",
        "location":"Chicago",
        "sale_id":53,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":22826,
        "date_sold":"1\/3\/2021",
        "car_id":53,
        "date_listed":"1\/5\/2020"
    },
    {
        "employee_id":70,
        "name":"Employee 70",
        "title":"Manager",
        "date_hired":"10\/31\/2020",
        "location":"Chicago",
        "sale_id":143,
        "car_make":"BMW",
        "car_model":"Civic",
        "price":63112,
        "date_sold":"9\/25\/2022",
        "car_id":143,
        "date_listed":"9\/26\/2021"
    },
    {
        "employee_id":70,
        "name":"Employee 70",
        "title":"Manager",
        "date_hired":"10\/31\/2020",
        "location":"Chicago",
        "sale_id":179,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":77351,
        "date_sold":"6\/4\/2023",
        "car_id":179,
        "date_listed":"6\/5\/2022"
    },
    {
        "employee_id":70,
        "name":"Employee 70",
        "title":"Manager",
        "date_hired":"10\/31\/2020",
        "location":"Chicago",
        "sale_id":180,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":51813,
        "date_sold":"6\/11\/2023",
        "car_id":180,
        "date_listed":"6\/12\/2022"
    },
    {
        "employee_id":71,
        "name":"Employee 71",
        "title":"Manager",
        "date_hired":"11\/30\/2020",
        "location":"Chicago",
        "sale_id":44,
        "car_make":"Toyota",
        "car_model":"Model Y",
        "price":46228,
        "date_sold":"11\/1\/2020",
        "car_id":44,
        "date_listed":"11\/3\/2019"
    },
    {
        "employee_id":71,
        "name":"Employee 71",
        "title":"Manager",
        "date_hired":"11\/30\/2020",
        "location":"Chicago",
        "sale_id":183,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":36121,
        "date_sold":"7\/2\/2023",
        "car_id":183,
        "date_listed":"7\/3\/2022"
    },
    {
        "employee_id":71,
        "name":"Employee 71",
        "title":"Manager",
        "date_hired":"11\/30\/2020",
        "location":"Chicago",
        "sale_id":194,
        "car_make":"BMW",
        "car_model":"Model X",
        "price":51352,
        "date_sold":"9\/17\/2023",
        "car_id":194,
        "date_listed":"9\/18\/2022"
    },
    {
        "employee_id":71,
        "name":"Employee 71",
        "title":"Manager",
        "date_hired":"11\/30\/2020",
        "location":"Chicago",
        "sale_id":200,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":65524,
        "date_sold":"10\/29\/2023",
        "car_id":200,
        "date_listed":"10\/30\/2022"
    },
    {
        "employee_id":72,
        "name":"Employee 72",
        "title":"Finance Officer",
        "date_hired":"12\/31\/2020",
        "location":"Miami",
        "sale_id":156,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":35068,
        "date_sold":"12\/25\/2022",
        "car_id":156,
        "date_listed":"12\/26\/2021"
    },
    {
        "employee_id":73,
        "name":"Employee 73",
        "title":"Finance Officer",
        "date_hired":"1\/31\/2021",
        "location":"New York",
        "sale_id":46,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":36339,
        "date_sold":"11\/15\/2020",
        "car_id":46,
        "date_listed":"11\/17\/2019"
    },
    {
        "employee_id":74,
        "name":"Employee 74",
        "title":"Salesman",
        "date_hired":"2\/28\/2021",
        "location":"Miami",
        "sale_id":182,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":21182,
        "date_sold":"6\/25\/2023",
        "car_id":182,
        "date_listed":"6\/26\/2022"
    },
    {
        "employee_id":76,
        "name":"Employee 76",
        "title":"Manager",
        "date_hired":"4\/30\/2021",
        "location":"New York",
        "sale_id":108,
        "car_make":"Toyota",
        "car_model":"Accord",
        "price":58454,
        "date_sold":"1\/23\/2022",
        "car_id":108,
        "date_listed":"1\/24\/2021"
    },
    {
        "employee_id":77,
        "name":"Employee 77",
        "title":"Salesman",
        "date_hired":"5\/31\/2021",
        "location":"New York",
        "sale_id":78,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":49196,
        "date_sold":"6\/27\/2021",
        "car_id":78,
        "date_listed":"6\/28\/2020"
    },
    {
        "employee_id":78,
        "name":"Employee 78",
        "title":"Salesman",
        "date_hired":"6\/30\/2021",
        "location":"Houston",
        "sale_id":155,
        "car_make":"BMW",
        "car_model":"Civic",
        "price":40629,
        "date_sold":"12\/18\/2022",
        "car_id":155,
        "date_listed":"12\/19\/2021"
    },
    {
        "employee_id":80,
        "name":"Employee 80",
        "title":"Manager",
        "date_hired":"8\/31\/2021",
        "location":"Los Angeles",
        "sale_id":136,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":50202,
        "date_sold":"8\/7\/2022",
        "car_id":136,
        "date_listed":"8\/8\/2021"
    },
    {
        "employee_id":81,
        "name":"Employee 81",
        "title":"Manager",
        "date_hired":"9\/30\/2021",
        "location":"Los Angeles",
        "sale_id":38,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":66783,
        "date_sold":"9\/20\/2020",
        "car_id":38,
        "date_listed":"9\/22\/2019"
    },
    {
        "employee_id":81,
        "name":"Employee 81",
        "title":"Manager",
        "date_hired":"9\/30\/2021",
        "location":"Los Angeles",
        "sale_id":75,
        "car_make":"Honda",
        "car_model":"Accord",
        "price":44398,
        "date_sold":"6\/6\/2021",
        "car_id":75,
        "date_listed":"6\/7\/2020"
    },
    {
        "employee_id":81,
        "name":"Employee 81",
        "title":"Manager",
        "date_hired":"9\/30\/2021",
        "location":"Los Angeles",
        "sale_id":134,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":66595,
        "date_sold":"7\/24\/2022",
        "car_id":134,
        "date_listed":"7\/25\/2021"
    },
    {
        "employee_id":81,
        "name":"Employee 81",
        "title":"Manager",
        "date_hired":"9\/30\/2021",
        "location":"Los Angeles",
        "sale_id":160,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":26843,
        "date_sold":"1\/22\/2023",
        "car_id":160,
        "date_listed":"1\/23\/2022"
    },
    {
        "employee_id":82,
        "name":"Employee 82",
        "title":"Finance Officer",
        "date_hired":"10\/31\/2021",
        "location":"Los Angeles",
        "sale_id":1,
        "car_make":"Ford",
        "car_model":"Civic",
        "price":71663,
        "date_sold":"1\/5\/2020",
        "car_id":1,
        "date_listed":"1\/6\/2019"
    },
    {
        "employee_id":82,
        "name":"Employee 82",
        "title":"Finance Officer",
        "date_hired":"10\/31\/2021",
        "location":"Los Angeles",
        "sale_id":60,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":68446,
        "date_sold":"2\/21\/2021",
        "car_id":60,
        "date_listed":"2\/23\/2020"
    },
    {
        "employee_id":82,
        "name":"Employee 82",
        "title":"Finance Officer",
        "date_hired":"10\/31\/2021",
        "location":"Los Angeles",
        "sale_id":168,
        "car_make":"Honda",
        "car_model":"Model X",
        "price":57612,
        "date_sold":"3\/19\/2023",
        "car_id":168,
        "date_listed":"3\/20\/2022"
    },
    {
        "employee_id":84,
        "name":"Employee 84",
        "title":"Salesman",
        "date_hired":"12\/31\/2021",
        "location":"Los Angeles",
        "sale_id":164,
        "car_make":"BMW",
        "car_model":"Camry",
        "price":26386,
        "date_sold":"2\/19\/2023",
        "car_id":164,
        "date_listed":"2\/20\/2022"
    },
    {
        "employee_id":84,
        "name":"Employee 84",
        "title":"Salesman",
        "date_hired":"12\/31\/2021",
        "location":"Los Angeles",
        "sale_id":195,
        "car_make":"Ford",
        "car_model":"Accord",
        "price":44166,
        "date_sold":"9\/24\/2023",
        "car_id":195,
        "date_listed":"9\/25\/2022"
    },
    {
        "employee_id":85,
        "name":"Employee 85",
        "title":"Manager",
        "date_hired":"1\/31\/2022",
        "location":"Chicago",
        "sale_id":36,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":38031,
        "date_sold":"9\/6\/2020",
        "car_id":36,
        "date_listed":"9\/8\/2019"
    },
    {
        "employee_id":85,
        "name":"Employee 85",
        "title":"Manager",
        "date_hired":"1\/31\/2022",
        "location":"Chicago",
        "sale_id":50,
        "car_make":"BMW",
        "car_model":"Civic",
        "price":75403,
        "date_sold":"12\/13\/2020",
        "car_id":50,
        "date_listed":"12\/15\/2019"
    },
    {
        "employee_id":85,
        "name":"Employee 85",
        "title":"Manager",
        "date_hired":"1\/31\/2022",
        "location":"Chicago",
        "sale_id":76,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":37170,
        "date_sold":"6\/13\/2021",
        "car_id":76,
        "date_listed":"6\/14\/2020"
    },
    {
        "employee_id":87,
        "name":"Employee 87",
        "title":"Manager",
        "date_hired":"3\/31\/2022",
        "location":"Chicago",
        "sale_id":125,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":48218,
        "date_sold":"5\/22\/2022",
        "car_id":125,
        "date_listed":"5\/23\/2021"
    },
    {
        "employee_id":88,
        "name":"Employee 88",
        "title":"Manager",
        "date_hired":"4\/30\/2022",
        "location":"Los Angeles",
        "sale_id":18,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":33568,
        "date_sold":"5\/3\/2020",
        "car_id":18,
        "date_listed":"5\/5\/2019"
    },
    {
        "employee_id":88,
        "name":"Employee 88",
        "title":"Manager",
        "date_hired":"4\/30\/2022",
        "location":"Los Angeles",
        "sale_id":130,
        "car_make":"Ford",
        "car_model":"Model X",
        "price":50180,
        "date_sold":"6\/26\/2022",
        "car_id":130,
        "date_listed":"6\/27\/2021"
    },
    {
        "employee_id":89,
        "name":"Employee 89",
        "title":"Finance Officer",
        "date_hired":"5\/31\/2022",
        "location":"Chicago",
        "sale_id":181,
        "car_make":"Toyota",
        "car_model":"Civic",
        "price":35115,
        "date_sold":"6\/18\/2023",
        "car_id":181,
        "date_listed":"6\/19\/2022"
    },
    {
        "employee_id":89,
        "name":"Employee 89",
        "title":"Finance Officer",
        "date_hired":"5\/31\/2022",
        "location":"Chicago",
        "sale_id":193,
        "car_make":"Toyota",
        "car_model":"Camry",
        "price":20274,
        "date_sold":"9\/10\/2023",
        "car_id":193,
        "date_listed":"9\/11\/2022"
    },
    {
        "employee_id":90,
        "name":"Employee 90",
        "title":"Finance Officer",
        "date_hired":"6\/30\/2022",
        "location":"Los Angeles",
        "sale_id":71,
        "car_make":"Mercedes",
        "car_model":"Model Y",
        "price":37663,
        "date_sold":"5\/9\/2021",
        "car_id":71,
        "date_listed":"5\/10\/2020"
    },
    {
        "employee_id":90,
        "name":"Employee 90",
        "title":"Finance Officer",
        "date_hired":"6\/30\/2022",
        "location":"Los Angeles",
        "sale_id":161,
        "car_make":"BMW",
        "car_model":"Model X",
        "price":60542,
        "date_sold":"1\/29\/2023",
        "car_id":161,
        "date_listed":"1\/30\/2022"
    },
    {
        "employee_id":92,
        "name":"Employee 92",
        "title":"Manager",
        "date_hired":"8\/31\/2022",
        "location":"Chicago",
        "sale_id":169,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":76523,
        "date_sold":"3\/26\/2023",
        "car_id":169,
        "date_listed":"3\/27\/2022"
    },
    {
        "employee_id":93,
        "name":"Employee 93",
        "title":"Salesman",
        "date_hired":"9\/30\/2022",
        "location":"Chicago",
        "sale_id":153,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":26729,
        "date_sold":"12\/4\/2022",
        "car_id":153,
        "date_listed":"12\/5\/2021"
    },
    {
        "employee_id":94,
        "name":"Employee 94",
        "title":"Salesman",
        "date_hired":"10\/31\/2022",
        "location":"Chicago",
        "sale_id":16,
        "car_make":"BMW",
        "car_model":"Accord",
        "price":79689,
        "date_sold":"4\/19\/2020",
        "car_id":16,
        "date_listed":"4\/21\/2019"
    },
    {
        "employee_id":94,
        "name":"Employee 94",
        "title":"Salesman",
        "date_hired":"10\/31\/2022",
        "location":"Chicago",
        "sale_id":110,
        "car_make":"Honda",
        "car_model":"Camry",
        "price":33247,
        "date_sold":"2\/6\/2022",
        "car_id":110,
        "date_listed":"2\/7\/2021"
    },
    {
        "employee_id":95,
        "name":"Employee 95",
        "title":"Manager",
        "date_hired":"11\/30\/2022",
        "location":"New York",
        "sale_id":97,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":68679,
        "date_sold":"11\/7\/2021",
        "car_id":97,
        "date_listed":"11\/8\/2020"
    },
    {
        "employee_id":96,
        "name":"Employee 96",
        "title":"Salesman",
        "date_hired":"12\/31\/2022",
        "location":"Houston",
        "sale_id":32,
        "car_make":"Mercedes",
        "car_model":"Camry",
        "price":57979,
        "date_sold":"8\/9\/2020",
        "car_id":32,
        "date_listed":"8\/11\/2019"
    },
    {
        "employee_id":96,
        "name":"Employee 96",
        "title":"Salesman",
        "date_hired":"12\/31\/2022",
        "location":"Houston",
        "sale_id":40,
        "car_make":"Toyota",
        "car_model":"Model X",
        "price":49210,
        "date_sold":"10\/4\/2020",
        "car_id":40,
        "date_listed":"10\/6\/2019"
    },
    {
        "employee_id":96,
        "name":"Employee 96",
        "title":"Salesman",
        "date_hired":"12\/31\/2022",
        "location":"Houston",
        "sale_id":49,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":35489,
        "date_sold":"12\/6\/2020",
        "car_id":49,
        "date_listed":"12\/8\/2019"
    },
    {
        "employee_id":98,
        "name":"Employee 98",
        "title":"Salesman",
        "date_hired":"2\/28\/2023",
        "location":"Miami",
        "sale_id":34,
        "car_make":"Honda",
        "car_model":"Model Y",
        "price":40279,
        "date_sold":"8\/23\/2020",
        "car_id":34,
        "date_listed":"8\/25\/2019"
    },
    {
        "employee_id":98,
        "name":"Employee 98",
        "title":"Salesman",
        "date_hired":"2\/28\/2023",
        "location":"Miami",
        "sale_id":67,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":34951,
        "date_sold":"4\/11\/2021",
        "car_id":67,
        "date_listed":"4\/12\/2020"
    },
    {
        "employee_id":98,
        "name":"Employee 98",
        "title":"Salesman",
        "date_hired":"2\/28\/2023",
        "location":"Miami",
        "sale_id":170,
        "car_make":"Mercedes",
        "car_model":"Model X",
        "price":32470,
        "date_sold":"4\/2\/2023",
        "car_id":170,
        "date_listed":"4\/3\/2022"
    },
    {
        "employee_id":99,
        "name":"Employee 99",
        "title":"Manager",
        "date_hired":"3\/31\/2023",
        "location":"Los Angeles",
        "sale_id":96,
        "car_make":"Ford",
        "car_model":"Camry",
        "price":71359,
        "date_sold":"10\/31\/2021",
        "car_id":96,
        "date_listed":"11\/1\/2020"
    },
    {
        "employee_id":99,
        "name":"Employee 99",
        "title":"Manager",
        "date_hired":"3\/31\/2023",
        "location":"Los Angeles",
        "sale_id":187,
        "car_make":"Mercedes",
        "car_model":"Civic",
        "price":46726,
        "date_sold":"7\/30\/2023",
        "car_id":187,
        "date_listed":"7\/31\/2022"
    },
    {
        "employee_id":100,
        "name":"Employee 100",
        "title":"Manager",
        "date_hired":"4\/30\/2023",
        "location":"New York",
        "sale_id":61,
        "car_make":"Mercedes",
        "car_model":"Accord",
        "price":43458,
        "date_sold":"2\/28\/2021",
        "car_id":61,
        "date_listed":"3\/1\/2020"
    },
    {
        "employee_id":100,
        "name":"Employee 100",
        "title":"Manager",
        "date_hired":"4\/30\/2023",
        "location":"New York",
        "sale_id":119,
        "car_make":"BMW",
        "car_model":"Model Y",
        "price":79000,
        "date_sold":"4\/10\/2022",
        "car_id":119,
        "date_listed":"4\/11\/2021"
    }
]